#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

root_uuid='2f15df07-1c58-4200-98c5-e022d9e419bf'
kernel_audio_options="ro quiet splash panic=3 panic_on_oops=1 module_blacklist=snd_hda_core,bluetooth mitigations=off pcie_aspm.policy=performance  cpufreq.default_governor=performance nohz=on nohz_full=all irqaffinity=0-1"

kernel_audio_version='5.17.0-rt15'
menuentry 'Ubuntu, Low Latency Audio' {
	linux /boot/vmlinuz-$kernel_audio_version root=UUID=$root_uuid $kernel_audio_options $vt_handoff
	initrd /boot/initrd.img-$kernel_audio_version
}
